### ISSUE TITLE
Episode 2

### ISSUE THREAD

**Issue by garricn** [SwiftCommunityPodcast/podcast#2] opened 2019-01-12 19:04 UTC
What should we do for Episode 2?

**Comment by salutis** [comment] 2019-01-16 21:33
Ideas:

* What are your setups (HW/SW) when coding in Swift?
* What do you personally want to see in the future versions of Swift and why?
* Will Swift ever be written in Swift so that the community can contribute?
* What are some fun stories from the early, pre-1.0 days?
* What the heck is Swift for TensorFlow?

**Comment by emanleet** [comment] 2019-01-16 22:04
* Swift on the Server
* Swift on Linux
* Swift Scripting

Really anything that shows the potential of Swift outside of Apple's ecosystem. Would love to start dabbling and learning about some cool things we can build with Swift.

**Comment by Killectro** [comment] 2019-01-17 05:07
A deep-dive on Swift for TensorFlow would be really awesome. I would love a better understanding of the changes in the forked Swift repo, what they might offer the language if/when they are upstreamed, etc.

**Comment by litianurazvan** [comment] 2019-01-17 07:56
As the name of the podcast implies, I would love to hear about tips on how to start a **local Swift Community**. 

- I've never attended to one so I'm curious what's the format of the meetup.
- How often do people meet.
- What other activities, besides presentations, are people doing.
- How to make people get involved

**Comment by marcocapano** [comment] 2019-01-17 09:56
> * Swift on the Server
> * Swift on Linux
> * Swift Scripting
> 
> Really anything that shows the potential of Swift outside of Apple's ecosystem. Would love to start dabbling and learning about some cool things we can build with Swift.

I feel like those could be split into multiple episodes, at least Server-side and scripting (maybe swift on linux is more related to swift on the server)

**Comment by Roslund** [comment] 2019-01-17 12:15
I would like to hear about concurrency:
* What is a Concurrency model?
* Actors
* Async Await

**Comment by VojtaStavik** [comment] 2019-01-17 12:45
Some topic ideas/questions:
- Swift 1/2 era was famous by constant SourceKit crashes. Can you talk a little bit about that and explain why is code completion so difficult?
- Do you think there will ever be direct interoperability between Swift and C++ (like we have for Swift and C)?

**Comment by JohnSundell** [comment] 2019-01-17 13:54
Concurrency could be a great topic for Episode 2 -- seems to be on many people's mind lately 👍 What do you think @lattner @garricn?

**Comment by grzegorzleszek** [comment] 2019-01-17 14:19
> Bring some of those people [that worked on Swift] to light , (..), there are people who made just the same amount of impact, but people don't know about them

_35:15 - 36:27_

I would love to hear their stories!

**Comment by valdirunars** [comment] 2019-01-17 14:46
Would love to hear one about swift as a tool for writing compilers/interpreters, Swift is pretty awesome for language parsing and I would love to hear from some of the creators of these awesome languages talk about their experience.

[Visual](https://github.com/NathanFlurry/VisualProgrammingLanguage)
[Cub](https://github.com/louisdh/cub)
[Trill](https://github.com/trill-lang/trill)

Btw. Writing a language in swift is loads of fun 😄 
[Zolang](https://github.com/zolang/Zolang)

**Comment by Kilo-Loco** [comment] 2019-01-17 14:53
I think having a swift community status report would be a good episode that can be done on a periodic basis (quarterly, annually, etc.)

What I mean is talk about how the swift community is continuing to grow and have the hosts share some of there favorite swift resources (blogs, videos, twitter accounts, podcasts).

I think it would also be nice to encourage people to contribute to the community and tell them how they can do so.

**Comment by mdiasdev** [comment] 2019-01-17 19:03
Performance tips and tricks.

People have written about how they analyzed build times to write more performant code. However, not a whole lot is written on how they found the individual offenders, realized it was them and not a bug, and chose the fix for the slower/un-performant code

**Comment by GlobeFlex** [comment] 2019-01-17 21:01
I would love to know if Swift will ever be viable for windows and .net users.  I love the .net core open source project that Microsoft is doing to bring .net cross platform.  It would be really huge for me if Swift could be available in Visual Studio.

**Comment by lattner** [comment] 2019-01-17 21:59
I think we should start by answering some community questions too that have come up.

**Comment by dlbuckley** [comment] 2019-01-18 09:48
Firstly I wan't to say that this was a great first podcast. It laid out exactly what you guys should use it for and I love that its open to contributions from everyone!

Having recently been through the swift evolution process for the first time with a tiny contribution to conform Range types to Codable, I felt there are still a few areas that feel hidden away from the community on core teams side. There are obviously forum discussions about a particular pitch etc, but it would be interesting to know what happens with:

- The internal process that chooses which pitches to pursue 
- The discussions on accepting a pitch or not after the review period has ended and how forum discussions influence the final decision
- How some of the great ideas that are thrown around on the forum are kept track of when they get seemingly buried after a short amount of time (and is that something that can be exposed to the community)
- How the decision for the next focus on a particular major version is taken, what influences are taken into account etc.

The forums didn't seem the right place to bring this up, but it would be really interesting from a podcast point of view.

Also I'm going to take one of @salutis's questions and change it slightly. Instead of asking "What are your setups (HW/SW) when coding in Swift?", my question is;

- Whats considered the most common setup for writing swift itself?

The guides give a few options and I used Xcode (as thats what I'm used to), but it felt incredibly clunky. So I would love to know if thats just the way things are or if there are better solutions the core team are using.

**Comment by TizianoCoroneo** [comment] 2019-01-19 01:00
I would love to hear Doug Gregor speaking about the origin and evolution of generics in Swift and the Generics Manifesto (https://github.com/apple/swift/blob/master/docs/GenericsManifesto.md)

**Comment by amw-zero** [comment] 2019-01-20 00:11
I’d love to hear about the functional influences and features of Swift. Swift obviously allows multi-paradigm design, but how much further will the functional part be pushed? It’s not as strict as Haskell or Elm, but would there be any chance of us getting additional features that could enforce the purity of functions? 

Does the community want a bigger focus on purity or do we want to keep the functional flavor that Swift currently affords? 

And finally, does Cocoa’s extreme object-oriented roots prevent the Swift community from going further down the functional path? There’s a lot of projects trying to emulate Elm andy React, but at the end of the day Cocoa is an imperative and OO API. Would the community want to do more if this wasn’t a restriction? Is it even a restriction and are teams using functional patterns in harmony with Cocoa?

**Comment by vjosullivan** [comment] 2019-01-20 13:20
> I think having a swift community status report would be a good episode that can be done on a periodic basis (quarterly, annually, etc.)
> 
> What I mean is talk about how the swift community is continuing to grow...

I know that the [Tiobe index](https://www.tiobe.com/tiobe-index/) has its limitations but is the best long-term measure of programming language that I am aware of.  Currently, it appears to indicate that the popularity of, and interest in Swift, [peaked in early 2017](https://www.tiobe.com/tiobe-index/swift/) and has been dropping since (other than a sizable blip in early 2018).  In addition, it appears also that [Objective-C](https://www.tiobe.com/tiobe-index/objective-c/) has overtaken Swift in popularity and risen back into their top ten languages table.

I'd be interested to hear what the team think of this, what the long-term road map for the language is (if any) and if they think it will ever become widely used for anything other than iOS app development.

Vince.

**Comment by salutis** [comment] 2019-01-21 14:50
@vjosullivan 

> [...] Objective-C has overtaken Swift [...]

Very interesting observation! Thanks for sharing.

**Comment by garricn** [comment] 2019-01-21 20:32
> > I think having a swift community status report would be a good episode that can be done on a periodic basis (quarterly, annually, etc.)
> > What I mean is talk about how the swift community is continuing to grow...
> 
> I know that the [Tiobe index](https://www.tiobe.com/tiobe-index/) has its limitations but it is the best long-term measure of programming language popularity and usage that I am aware of. Currently, it appears to indicate that the popularity of, and interest in Swift, [peaked in early 2017](https://www.tiobe.com/tiobe-index/swift/) and has been dropping since (other than a sizable blip in early 2018). In addition, it appears also that [Objective-C](https://www.tiobe.com/tiobe-index/objective-c/) has overtaken Swift in popularity and risen back into their top ten languages table.
> 
> I'd be interested to hear what the team think of this, what the long-term road map for the language is (in particular, who it is aimed at) and if they think it will ever become widely used for anything other than iOS app development.
> 
> Vince.
> 
> Addendum: I’m somewhat surprised and disappointed to see my comment marked as “closed”. Could anyone explain why such a move was necessary? I didn’t listen to all the podcast in one go and I see that the latter part of the podcast did talk about Swift outside of iOS app development. However, I'm still curious to hear opinions on the apparent decline in popularity of Swift and resurgence in interest in Objective-C (both trends I’m very doubtful about, myself).

I don’t think your comment was closed. Someone referenced this issue in another issue and that issue was closed.

**Comment by ivanglushko** [comment] 2019-01-21 23:16
Maybe touch on such subjects as scripting in swift, RxSwift, Mac OS development (how to transition from iOS to Mac OS cause there are tons literature about iOS  dev and none on MacOS /swift ) I'm interested in open source as well, how does one creates a tool? Like John's many projects it seems overwhelming.

**Comment by Shehryar-ASAPP** [comment] 2019-01-22 17:17
Goals for making Swift more available outside of just the Apple ecosystem:
* Server side swift
* Swift -> WASM

Probably even a whole episode on package management.

**Comment by Shehryar** [comment] 2019-01-22 17:19
Goals for making Swift more available outside of just the Apple ecosystem:
* Server side swift
* Swift -> WASM

Probably even a whole episode on package management.

**Comment by GrfxGuru** [comment] 2019-01-26 23:34
I would love to hear some thoughts and discussion on Serverside for sure as many have mentioned. I am also curious about using Swift as an automation tool, scripting or otherwise on macOS. It feels like it would be a great step forward from Automator and AppleScript.

As someone that always appreciated but never deeply got into AppleScript, it seems like a great way to bring automation into the current century :)

**Comment by djavan-tagheuer** [comment] 2019-01-30 10:07
I would love to hear what you think about the recent patents filled by Apple on some Swift parts.

Sources:
- https://www.theregister.co.uk/2019/01/26/apples_swift_patents/
- https://forums.swift.org/t/apple-is-indeed-patenting-swift-features/19779

**Comment by djavan-bertrand** [comment] 2019-01-30 10:13
Hi,
I would love to hear what you think about the fact that Apple recently patented some parts of the Swift language.

Sources:
- [The Register](https://www.theregister.co.uk/2019/01/26/apples_swift_patents/)
- [Swift forum](https://forums.swift.org/t/apple-is-indeed-patenting-swift-features/19779)

Thanks !

**Comment by bobasheville** [comment] 2019-01-31 21:05
I helped start an App Development Camp at the high school where I work. Garric was kind enough to feature our App Camp last December on an episode of the Swift Coders Podcast. We teach 13-18 year olds how to develop their own apps with Swift during a 1-week camp. Since 2015, several of our students have started to develop into Teacher Assistants and Teachers as they gained more experience with Xcode and debugging. It would be interesting to hear an episode where our students discuss what they love about learning and teaching Swift. I believe our students have some interesting perspectives to share. I'm thinking of one alum who is now a student at GA Tech and another senior who plans to study computer science at Carnegie Mellon this fall.

Another episode idea: I would love to hear more from members of the Swift community who are using open source frameworks like AudioKit in their apps.

**Comment by rcgottlieb** [comment] 2019-02-02 04:07
I'd like to see an episode on all of the tools you use for writing Swift outside of Xcode and/or doing an episode on Xcode itself as it applies to Swift (coding, debugging, running, etc). The tools outside of Xcode could be anything for iOS, macOS and server side. I'm curious if anyone is writing an IDE for the server or if Xcode still works good for that as well, and if so, how do you write for the server.

**Comment by marcusrossel** [comment] 2019-02-17 09:56
@garricn Should this issue be closed as it is not immediately relevant anymore?

**Closed** 2019-02-17 16:27 UTC
